name: sio2_renovations_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1
  widget_and_text_animator: ^1.1.5
  rive: ^0.13.20
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  cookie_consent: ^1.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  visibility_detector: ^0.4.0+2
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  fade_out_particle: ^1.2.2
  animated_text_kit: ^4.2.3
  carousel_slider_plus: ^7.1.0
  flutter_staggered_grid_view: ^0.7.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/rive/
    - local.env

  fonts:
    - family: DancingScript
      fonts: 
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
