// AUTO-GENERATED — do not edit manually.
// Source: hub_sio2renovations/content/article/*.md
// Regenerated by scripts/generate-articles-dart.js on every push to main.

const List<Map<String, String>> articlesData = [
  {
    "category": "LOFT & ATELIER",
    "title": "Rénovation loft et atelier : guide complet des travaux",
    "description": "Rénover un atelier en loft coûte 50 000 à 125 000 € — réseaux à créer de zéro, isolation à...",
    "image": "https://hub.sio2renovations.com/images/articles/loft-atelier-montreuil.webp",
    "url": "https://hub.sio2renovations.com/articles/renovation-loft-atelier?ref=sio2renovations",
  },
  {
    "category": "SALLE DE BAINS",
    "title": "Rénover une salle de bains à Paris : coûts, délais et autorisations 2026",
    "description": "Rénover une salle de bains à Paris coûte entre 1 000 et 3 000 €/m² — 20 à 30 % de plus...",
    "image": "https://hub.sio2renovations.com/images/articles/sdb-cover.webp",
    "url": "https://hub.sio2renovations.com/articles/renovation-salle-de-bains-paris?ref=sio2renovations",
  },
  {
    "category": "APPARTEMENT",
    "title": "Rénover un appartement à Paris : guide complet 2026",
    "description": "Rénovation légère à lourde à Paris : coûts réalistes 2026 (400 à 3 500 €/m²),...",
    "image": "https://hub.sio2renovations.com/images/articles/renovation-appartement-paris.jpg",
    "url": "https://hub.sio2renovations.com/articles/renovation-appartement-paris-guide-complet?ref=sio2renovations",
  },
];
